services:
  # Backend service
  - type: web
    name: kalkulator-rab-api
    env: node
    buildCommand: npm install
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
    
  # Frontend service
  - type: web
    name: kalkulator-rab-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_API_URL
        value: https://kalkulator-rab-api.onrender.com 